[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
metaplex_core_test = "3cZRCznQLmZtzKiRYR1QX9H8WgA2fb4f4ELXGpasm1Mp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/development/metaplex-core-staking-contract/keys/deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
